/**
 * `BLOOM_RELEASE_CONTRACT` — the confirmed requirements structural checks are
 * measured against. It contains ONLY confirmed requirements (F-034..F-037,
 * F-050..F-055): required routes, features, runtime sources, renderer
 * requirements derived from the platform registries, the canonical Publications
 * data contract and the Bloom cart-drawer / preview-demo contract descriptors
 * generated by the extracted helpers.
 *
 * This is a pure data + builder module: it imports the platform registries and
 * the extracted cart-drawer / preview-cart helpers, but performs no I/O.
 */

import {
  PAGE_REGISTRY,
  PRODUCT_UNIFIED_THEMES,
  CART_SECTION_THEMES,
} from '../page-registry';
import { bloomRegistry } from '../../generator/registries/bloom';
import { buildPreviewCartDemoScript } from '../preview-cart-contract';

/** A required page (manifest seed + PAGE_REGISTRY route). */
export interface RequiredPage {
  id: string;
  route: string;
  kind: 'content' | 'verbatim';
  chrome: 'full' | 'checkout' | 'none';
  /** verbatim/theme-file routes require both source + standalone live output. */
  requiresStandaloneOutput: boolean;
}

/** A required generator/section renderer entry. */
export interface RequiredRenderer {
  name: string;
  importPath: string;
}

/** The confirmed Bloom release contract. */
export interface BloomReleaseContract {
  theme: string;
  pages: RequiredPage[];
  /** required feature flags (must be declared AND enabled). */
  features: string[];
  /** required runtime source files (repo-relative). */
  runtimeSources: string[];
  /** required renderers derived from PAGE_REGISTRY + registries + section map. */
  renderers: RequiredRenderer[];
  /** unified-product / cart-section theme membership (behavior context). */
  productUnified: boolean;
  cartSection: boolean;
  /** canonical Publications data contract (F-050) vs mapped renderer (F-055). */
  publications: {
    /** shared canonical contract (nullish precedence, Math.trunc, clamp 1..4). */
    canonical: { clampMin: number; clampMax: number; fallback: number; rounding: 'trunc' };
    /** the Bloom mapped renderer’s DIVERGENT behavior on the target ref. */
    mappedRenderer: { maxColumns: number; maxCards: number; rounding: 'round' };
  };
  /** cart-drawer + preview-demo contract from the extracted helpers. */
  cartDrawer: {
    /** the five exact optional globals. */
    globals: string[];
    /** SCHEME couples DISCLAIMER. */
    coupled: [string, string];
    /** the three independent trimmed text globals. */
    optionalText: string[];
    /** preview-only demo seed contract. */
    previewDemo: {
      storageKey: string;
      updatedEvent: string;
      endpoint: { method: string; route: string };
      lineItemMarker: string;
      /** live mode must contain NEITHER seed script NOR its line item. */
      previewOnly: true;
    };
    /** call-site reachability the contract REQUIRES (built-theme must inject). */
    requiredCallSites: {
      v2Sections: boolean;
      builtTheme: boolean;
      liveBuild: boolean;
    };
  };
}

const BLOOM = 'bloom';

/** Required runtime source files named by the contract (F-037 all-open). */
export const BLOOM_REQUIRED_RUNTIME_SOURCES: readonly string[] = [
  'themes/bloom/src/lib/cart.ts',
  'themes/bloom/src/lib/nt-cart-bloom.ts',
  'themes/bloom/src/lib/cart-thumb-html.ts',
  'themes/bloom/src/lib/wishlist.ts',
  'themes/bloom/src/lib/auth.ts',
  'themes/bloom/src/lib/storefront-hydrate.ts',
];

/** Build the confirmed release contract for Bloom. */
function buildContract(): BloomReleaseContract {
  const pages: RequiredPage[] = PAGE_REGISTRY.map((e) => ({
    id: e.id,
    route: e.route,
    kind: e.kind,
    chrome: e.chrome,
    // verbatim/theme-file routes require their standalone live output too.
    requiresStandaloneOutput: e.kind === 'verbatim',
  }));

  const renderers: RequiredRenderer[] = Object.entries(bloomRegistry)
    .map(([name, entry]) => ({
      name,
      importPath: (entry as { importPath: string }).importPath,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  // Generate the preview-demo contract from the REAL extracted helper so the
  // contract cannot drift from the generator.
  const script = buildPreviewCartDemoScript('__SITE__', BLOOM);
  void script; // presence is asserted structurally by storefront inventory.

  return {
    theme: BLOOM,
    pages,
    features: ['benefits', 'wishlist'],
    runtimeSources: [...BLOOM_REQUIRED_RUNTIME_SOURCES],
    renderers,
    productUnified: PRODUCT_UNIFIED_THEMES.has(BLOOM),
    cartSection: CART_SECTION_THEMES.has(BLOOM),
    publications: {
      canonical: { clampMin: 1, clampMax: 4, fallback: 3, rounding: 'trunc' },
      mappedRenderer: { maxColumns: 6, maxCards: 12, rounding: 'round' },
    },
    cartDrawer: {
      globals: [
        '__MERFY_CART_DRAWER_SCHEME__',
        '__MERFY_CART_DRAWER_DISCLAIMER__',
        '__MERFY_CART_DRAWER_TITLE__',
        '__MERFY_CART_DRAWER_CHECKOUT__',
        '__MERFY_CART_DRAWER_EMPTY__',
      ],
      coupled: ['__MERFY_CART_DRAWER_SCHEME__', '__MERFY_CART_DRAWER_DISCLAIMER__'],
      optionalText: [
        '__MERFY_CART_DRAWER_TITLE__',
        '__MERFY_CART_DRAWER_CHECKOUT__',
        '__MERFY_CART_DRAWER_EMPTY__',
      ],
      previewDemo: {
        storageKey: 'bloom:cart:v1',
        updatedEvent: 'bloom:cart:updated',
        endpoint: { method: 'GET', route: '/api/sites/{param}/storefront-data' },
        lineItemMarker: 'preview-demo',
        previewOnly: true,
      },
      // The contract REQUIRES the built-theme path to inject drawer globals; on
      // the target ref it does NOT (F-053) → structural GAP.
      requiredCallSites: { v2Sections: true, builtTheme: true, liveBuild: true },
    },
  };
}

export const BLOOM_RELEASE_CONTRACT: BloomReleaseContract = buildContract();
