import type { Product } from '../../types';

const placeholder = (id: number) => `https://placehold.co/600x800?text=Product+${id}`;

/**
 * 50+ realistic mock products with Russian names, RUB prices (in kopecks),
 * and placeholder images for development and testing.
 */
export const mockProducts: Product[] = [
  {
    id: 'prod_1',
    handle: 'cotton-tee',
    title: 'Хлопковая футболка',
    description: 'Мягкая футболка из 100% хлопка. Идеально для повседневной носки.',
    price: 299000,
    compareAtPrice: 399000,
    images: [{ url: placeholder(1), alt: 'Хлопковая футболка' }],
    variants: [
      { id: 'var_1_s', title: 'S', price: 299000, available: true, options: { size: 'S' } },
      { id: 'var_1_m', title: 'M', price: 299000, available: true, options: { size: 'M' } },
      { id: 'var_1_l', title: 'L', price: 299000, available: true, options: { size: 'L' } },
      { id: 'var_1_xl', title: 'XL', price: 299000, available: false, options: { size: 'XL' } },
    ],
    tags: ['футболки', 'хлопок', 'лето'],
    vendor: 'Merfy Basics',
    productType: 'Футболки',
  },
  {
    id: 'prod_2',
    handle: 'denim-jacket',
    title: 'Джинсовая куртка',
    description: 'Классическая джинсовая куртка с медными пуговицами.',
    price: 599000,
    images: [{ url: placeholder(2), alt: 'Джинсовая куртка' }],
    variants: [
      { id: 'var_2_s', title: 'S', price: 599000, available: true, options: { size: 'S' } },
      { id: 'var_2_m', title: 'M', price: 599000, available: true, options: { size: 'M' } },
      { id: 'var_2_l', title: 'L', price: 599000, available: true, options: { size: 'L' } },
    ],
    tags: ['куртки', 'деним', 'весна'],
    vendor: 'Merfy Denim',
    productType: 'Куртки',
  },
  {
    id: 'prod_3',
    handle: 'summer-dress',
    title: 'Летнее платье',
    description: 'Легкое платье из вискозы с цветочным принтом.',
    price: 449000,
    compareAtPrice: 549000,
    images: [{ url: placeholder(3), alt: 'Летнее платье' }],
    variants: [
      { id: 'var_3_xs', title: 'XS', price: 449000, available: true, options: { size: 'XS' } },
      { id: 'var_3_s', title: 'S', price: 449000, available: true, options: { size: 'S' } },
      { id: 'var_3_m', title: 'M', price: 449000, available: true, options: { size: 'M' } },
    ],
    tags: ['платья', 'лето', 'цветочный'],
    vendor: 'Merfy Style',
    productType: 'Платья',
  },
  {
    id: 'prod_4',
    handle: 'wool-sweater',
    title: 'Шерстяной свитер',
    description: 'Теплый свитер из мериносовой шерсти.',
    price: 789000,
    images: [{ url: placeholder(4), alt: 'Шерстяной свитер' }],
    variants: [
      { id: 'var_4_m', title: 'M', price: 789000, available: true, options: { size: 'M' } },
      { id: 'var_4_l', title: 'L', price: 789000, available: true, options: { size: 'L' } },
    ],
    tags: ['свитеры', 'шерсть', 'зима'],
    vendor: 'Merfy Knit',
    productType: 'Свитеры',
  },
  {
    id: 'prod_5',
    handle: 'leather-belt',
    title: 'Кожаный ремень',
    description: 'Ремень из натуральной кожи с классической пряжкой.',
    price: 249000,
    images: [{ url: placeholder(5), alt: 'Кожаный ремень' }],
    variants: [
      { id: 'var_5_default', title: 'Один размер', price: 249000, available: true },
    ],
    tags: ['аксессуары', 'кожа'],
    vendor: 'Merfy Accessories',
    productType: 'Аксессуары',
  },
  {
    id: 'prod_6',
    handle: 'canvas-sneakers',
    title: 'Кеды из канваса',
    description: 'Удобные кеды для городских прогулок.',
    price: 349000,
    images: [{ url: placeholder(6), alt: 'Кеды из канваса' }],
    variants: [
      { id: 'var_6_38', title: '38', price: 349000, available: true, options: { size: '38' } },
      { id: 'var_6_39', title: '39', price: 349000, available: true, options: { size: '39' } },
      { id: 'var_6_40', title: '40', price: 349000, available: true, options: { size: '40' } },
      { id: 'var_6_41', title: '41', price: 349000, available: true, options: { size: '41' } },
      { id: 'var_6_42', title: '42', price: 349000, available: false, options: { size: '42' } },
    ],
    tags: ['обувь', 'кеды', 'лето'],
    vendor: 'Merfy Shoes',
    productType: 'Обувь',
  },
  {
    id: 'prod_7',
    handle: 'silk-scarf',
    title: 'Шелковый шарф',
    description: 'Элегантный шелковый шарф с абстрактным принтом.',
    price: 189000,
    compareAtPrice: 259000,
    images: [{ url: placeholder(7), alt: 'Шелковый шарф' }],
    variants: [
      { id: 'var_7_default', title: 'Один размер', price: 189000, available: true },
    ],
    tags: ['аксессуары', 'шелк', 'подарок'],
    vendor: 'Merfy Accessories',
    productType: 'Аксессуары',
  },
  {
    id: 'prod_8',
    handle: 'linen-pants',
    title: 'Льняные брюки',
    description: 'Легкие льняные брюки свободного кроя.',
    price: 499000,
    images: [{ url: placeholder(8), alt: 'Льняные брюки' }],
    variants: [
      { id: 'var_8_s', title: 'S', price: 499000, available: true, options: { size: 'S' } },
      { id: 'var_8_m', title: 'M', price: 499000, available: true, options: { size: 'M' } },
      { id: 'var_8_l', title: 'L', price: 499000, available: true, options: { size: 'L' } },
    ],
    tags: ['брюки', 'лен', 'лето'],
    vendor: 'Merfy Basics',
    productType: 'Брюки',
  },
  {
    id: 'prod_9',
    handle: 'oversized-hoodie',
    title: 'Худи оверсайз',
    description: 'Объемное худи из плотного хлопка с начесом.',
    price: 459000,
    images: [{ url: placeholder(9), alt: 'Худи оверсайз' }],
    variants: [
      { id: 'var_9_m', title: 'M', price: 459000, available: true, options: { size: 'M' } },
      { id: 'var_9_l', title: 'L', price: 459000, available: true, options: { size: 'L' } },
      { id: 'var_9_xl', title: 'XL', price: 459000, available: true, options: { size: 'XL' } },
    ],
    tags: ['худи', 'оверсайз', 'осень'],
    vendor: 'Merfy Street',
    productType: 'Худи',
  },
  {
    id: 'prod_10',
    handle: 'mini-skirt',
    title: 'Мини-юбка',
    description: 'Стильная мини-юбка из экокожи.',
    price: 329000,
    images: [{ url: placeholder(10), alt: 'Мини-юбка' }],
    variants: [
      { id: 'var_10_xs', title: 'XS', price: 329000, available: true, options: { size: 'XS' } },
      { id: 'var_10_s', title: 'S', price: 329000, available: true, options: { size: 'S' } },
      { id: 'var_10_m', title: 'M', price: 329000, available: false, options: { size: 'M' } },
    ],
    tags: ['юбки', 'экокожа'],
    vendor: 'Merfy Style',
    productType: 'Юбки',
  },
  {
    id: 'prod_11',
    handle: 'cashmere-beanie',
    title: 'Кашемировая шапка',
    description: 'Мягкая шапка из кашемира.',
    price: 359000,
    images: [{ url: placeholder(11), alt: 'Кашемировая шапка' }],
    variants: [
      { id: 'var_11_default', title: 'Один размер', price: 359000, available: true },
    ],
    tags: ['аксессуары', 'кашемир', 'зима'],
    vendor: 'Merfy Knit',
    productType: 'Аксессуары',
  },
  {
    id: 'prod_12',
    handle: 'striped-polo',
    title: 'Поло в полоску',
    description: 'Классическое поло из хлопка пике.',
    price: 279000,
    images: [{ url: placeholder(12), alt: 'Поло в полоску' }],
    variants: [
      { id: 'var_12_s', title: 'S', price: 279000, available: true, options: { size: 'S' } },
      { id: 'var_12_m', title: 'M', price: 279000, available: true, options: { size: 'M' } },
      { id: 'var_12_l', title: 'L', price: 279000, available: true, options: { size: 'L' } },
    ],
    tags: ['поло', 'полоска', 'лето'],
    vendor: 'Merfy Basics',
    productType: 'Поло',
  },
  {
    id: 'prod_13',
    handle: 'rain-jacket',
    title: 'Дождевик',
    description: 'Водонепроницаемая куртка с капюшоном.',
    price: 399000,
    images: [{ url: placeholder(13), alt: 'Дождевик' }],
    variants: [
      { id: 'var_13_m', title: 'M', price: 399000, available: true, options: { size: 'M' } },
      { id: 'var_13_l', title: 'L', price: 399000, available: true, options: { size: 'L' } },
    ],
    tags: ['куртки', 'дождевик', 'осень'],
    vendor: 'Merfy Outerwear',
    productType: 'Куртки',
  },
  {
    id: 'prod_14',
    handle: 'yoga-leggings',
    title: 'Леггинсы для йоги',
    description: 'Эластичные леггинсы с высокой посадкой.',
    price: 289000,
    images: [{ url: placeholder(14), alt: 'Леггинсы для йоги' }],
    variants: [
      { id: 'var_14_xs', title: 'XS', price: 289000, available: true, options: { size: 'XS' } },
      { id: 'var_14_s', title: 'S', price: 289000, available: true, options: { size: 'S' } },
      { id: 'var_14_m', title: 'M', price: 289000, available: true, options: { size: 'M' } },
      { id: 'var_14_l', title: 'L', price: 289000, available: true, options: { size: 'L' } },
    ],
    tags: ['спорт', 'йога', 'леггинсы'],
    vendor: 'Merfy Active',
    productType: 'Леггинсы',
  },
  {
    id: 'prod_15',
    handle: 'bomber-jacket',
    title: 'Бомбер',
    description: 'Куртка-бомбер с нашивкой на спине.',
    price: 679000,
    images: [{ url: placeholder(15), alt: 'Бомбер' }],
    variants: [
      { id: 'var_15_m', title: 'M', price: 679000, available: true, options: { size: 'M' } },
      { id: 'var_15_l', title: 'L', price: 679000, available: true, options: { size: 'L' } },
      { id: 'var_15_xl', title: 'XL', price: 679000, available: false, options: { size: 'XL' } },
    ],
    tags: ['куртки', 'бомбер', 'весна'],
    vendor: 'Merfy Street',
    productType: 'Куртки',
  },
  {
    id: 'prod_16',
    handle: 'cotton-socks-pack',
    title: 'Набор хлопковых носков (3 пары)',
    description: 'Три пары носков из органического хлопка.',
    price: 99000,
    images: [{ url: placeholder(16), alt: 'Набор носков' }],
    variants: [
      { id: 'var_16_default', title: 'Один размер', price: 99000, available: true },
    ],
    tags: ['аксессуары', 'носки', 'хлопок'],
    vendor: 'Merfy Basics',
    productType: 'Аксессуары',
  },
  {
    id: 'prod_17',
    handle: 'maxi-dress',
    title: 'Макси-платье',
    description: 'Длинное платье из хлопка для жаркого лета.',
    price: 529000,
    images: [{ url: placeholder(17), alt: 'Макси-платье' }],
    variants: [
      { id: 'var_17_s', title: 'S', price: 529000, available: true, options: { size: 'S' } },
      { id: 'var_17_m', title: 'M', price: 529000, available: true, options: { size: 'M' } },
      { id: 'var_17_l', title: 'L', price: 529000, available: true, options: { size: 'L' } },
    ],
    tags: ['платья', 'макси', 'лето'],
    vendor: 'Merfy Style',
    productType: 'Платья',
  },
  {
    id: 'prod_18',
    handle: 'cargo-pants',
    title: 'Брюки карго',
    description: 'Широкие брюки карго с боковыми карманами.',
    price: 469000,
    images: [{ url: placeholder(18), alt: 'Брюки карго' }],
    variants: [
      { id: 'var_18_s', title: 'S', price: 469000, available: true, options: { size: 'S' } },
      { id: 'var_18_m', title: 'M', price: 469000, available: true, options: { size: 'M' } },
      { id: 'var_18_l', title: 'L', price: 469000, available: true, options: { size: 'L' } },
    ],
    tags: ['брюки', 'карго', 'уличный стиль'],
    vendor: 'Merfy Street',
    productType: 'Брюки',
  },
  {
    id: 'prod_19',
    handle: 'crossbody-bag',
    title: 'Сумка через плечо',
    description: 'Компактная сумка из экокожи.',
    price: 379000,
    images: [{ url: placeholder(19), alt: 'Сумка через плечо' }],
    variants: [
      { id: 'var_19_black', title: 'Черная', price: 379000, available: true, options: { color: 'black' } },
      { id: 'var_19_beige', title: 'Бежевая', price: 379000, available: true, options: { color: 'beige' } },
    ],
    tags: ['сумки', 'экокожа', 'аксессуары'],
    vendor: 'Merfy Accessories',
    productType: 'Сумки',
  },
  {
    id: 'prod_20',
    handle: 'print-tshirt',
    title: 'Футболка с принтом',
    description: 'Футболка оверсайз с авторским принтом.',
    price: 259000,
    images: [{ url: placeholder(20), alt: 'Футболка с принтом' }],
    variants: [
      { id: 'var_20_m', title: 'M', price: 259000, available: true, options: { size: 'M' } },
      { id: 'var_20_l', title: 'L', price: 259000, available: true, options: { size: 'L' } },
      { id: 'var_20_xl', title: 'XL', price: 259000, available: true, options: { size: 'XL' } },
    ],
    tags: ['футболки', 'принт', 'оверсайз'],
    vendor: 'Merfy Street',
    productType: 'Футболки',
  },
  {
    id: 'prod_21',
    handle: 'blazer-classic',
    title: 'Блейзер классический',
    description: 'Классический блейзер из костюмной ткани.',
    price: 899000,
    images: [{ url: placeholder(21), alt: 'Блейзер классический' }],
    variants: [
      { id: 'var_21_s', title: 'S', price: 899000, available: true, options: { size: 'S' } },
      { id: 'var_21_m', title: 'M', price: 899000, available: true, options: { size: 'M' } },
      { id: 'var_21_l', title: 'L', price: 899000, available: false, options: { size: 'L' } },
    ],
    tags: ['пиджаки', 'классика', 'офис'],
    vendor: 'Merfy Classic',
    productType: 'Пиджаки',
  },
  {
    id: 'prod_22',
    handle: 'chino-shorts',
    title: 'Шорты чино',
    description: 'Шорты из хлопка длиной до колена.',
    price: 269000,
    images: [{ url: placeholder(22), alt: 'Шорты чино' }],
    variants: [
      { id: 'var_22_s', title: 'S', price: 269000, available: true, options: { size: 'S' } },
      { id: 'var_22_m', title: 'M', price: 269000, available: true, options: { size: 'M' } },
      { id: 'var_22_l', title: 'L', price: 269000, available: true, options: { size: 'L' } },
    ],
    tags: ['шорты', 'чино', 'лето'],
    vendor: 'Merfy Basics',
    productType: 'Шорты',
  },
  {
    id: 'prod_23',
    handle: 'tote-bag',
    title: 'Тоут сумка',
    description: 'Большая тканевая сумка-тоут.',
    price: 199000,
    images: [{ url: placeholder(23), alt: 'Тоут сумка' }],
    variants: [
      { id: 'var_23_default', title: 'Один размер', price: 199000, available: true },
    ],
    tags: ['сумки', 'ткань', 'эко'],
    vendor: 'Merfy Accessories',
    productType: 'Сумки',
  },
  {
    id: 'prod_24',
    handle: 'knit-cardigan',
    title: 'Вязаный кардиган',
    description: 'Длинный кардиган крупной вязки.',
    price: 649000,
    images: [{ url: placeholder(24), alt: 'Вязаный кардиган' }],
    variants: [
      { id: 'var_24_s', title: 'S', price: 649000, available: true, options: { size: 'S' } },
      { id: 'var_24_m', title: 'M', price: 649000, available: true, options: { size: 'M' } },
    ],
    tags: ['кардиганы', 'вязка', 'осень'],
    vendor: 'Merfy Knit',
    productType: 'Кардиганы',
  },
  {
    id: 'prod_25',
    handle: 'sunglasses-round',
    title: 'Круглые солнцезащитные очки',
    description: 'Очки в тонкой металлической оправе.',
    price: 219000,
    images: [{ url: placeholder(25), alt: 'Круглые солнцезащитные очки' }],
    variants: [
      { id: 'var_25_default', title: 'Один размер', price: 219000, available: true },
    ],
    tags: ['аксессуары', 'очки', 'лето'],
    vendor: 'Merfy Accessories',
    productType: 'Аксессуары',
  },
  {
    id: 'prod_26',
    handle: 'wrap-blouse',
    title: 'Блуза с запахом',
    description: 'Элегантная блуза с V-образным вырезом.',
    price: 389000,
    images: [{ url: placeholder(26), alt: 'Блуза с запахом' }],
    variants: [
      { id: 'var_26_xs', title: 'XS', price: 389000, available: true, options: { size: 'XS' } },
      { id: 'var_26_s', title: 'S', price: 389000, available: true, options: { size: 'S' } },
      { id: 'var_26_m', title: 'M', price: 389000, available: true, options: { size: 'M' } },
    ],
    tags: ['блузы', 'офис', 'элегантность'],
    vendor: 'Merfy Classic',
    productType: 'Блузы',
  },
  {
    id: 'prod_27',
    handle: 'jogger-pants',
    title: 'Джоггеры',
    description: 'Спортивные штаны с манжетами.',
    price: 329000,
    images: [{ url: placeholder(27), alt: 'Джоггеры' }],
    variants: [
      { id: 'var_27_s', title: 'S', price: 329000, available: true, options: { size: 'S' } },
      { id: 'var_27_m', title: 'M', price: 329000, available: true, options: { size: 'M' } },
      { id: 'var_27_l', title: 'L', price: 329000, available: true, options: { size: 'L' } },
    ],
    tags: ['брюки', 'спорт', 'джоггеры'],
    vendor: 'Merfy Active',
    productType: 'Брюки',
  },
  {
    id: 'prod_28',
    handle: 'bucket-hat',
    title: 'Панама',
    description: 'Панама из хлопка с широкими полями.',
    price: 159000,
    images: [{ url: placeholder(28), alt: 'Панама' }],
    variants: [
      { id: 'var_28_default', title: 'Один размер', price: 159000, available: true },
    ],
    tags: ['аксессуары', 'шляпы', 'лето'],
    vendor: 'Merfy Accessories',
    productType: 'Аксессуары',
  },
  {
    id: 'prod_29',
    handle: 'wide-leg-jeans',
    title: 'Широкие джинсы',
    description: 'Джинсы широкого кроя из плотного денима.',
    price: 549000,
    images: [{ url: placeholder(29), alt: 'Широкие джинсы' }],
    variants: [
      { id: 'var_29_26', title: '26', price: 549000, available: true, options: { size: '26' } },
      { id: 'var_29_28', title: '28', price: 549000, available: true, options: { size: '28' } },
      { id: 'var_29_30', title: '30', price: 549000, available: true, options: { size: '30' } },
      { id: 'var_29_32', title: '32', price: 549000, available: false, options: { size: '32' } },
    ],
    tags: ['джинсы', 'широкие', 'деним'],
    vendor: 'Merfy Denim',
    productType: 'Джинсы',
  },
  {
    id: 'prod_30',
    handle: 'merino-gloves',
    title: 'Перчатки из мериноса',
    description: 'Мягкие перчатки для холодной погоды.',
    price: 179000,
    images: [{ url: placeholder(30), alt: 'Перчатки из мериноса' }],
    variants: [
      { id: 'var_30_s', title: 'S/M', price: 179000, available: true, options: { size: 'S/M' } },
      { id: 'var_30_l', title: 'L/XL', price: 179000, available: true, options: { size: 'L/XL' } },
    ],
    tags: ['аксессуары', 'перчатки', 'зима'],
    vendor: 'Merfy Knit',
    productType: 'Аксессуары',
  },
  {
    id: 'prod_31',
    handle: 'trench-coat',
    title: 'Тренч',
    description: 'Классический тренч из водоотталкивающей ткани.',
    price: 1199000,
    images: [{ url: placeholder(31), alt: 'Тренч' }],
    variants: [
      { id: 'var_31_s', title: 'S', price: 1199000, available: true, options: { size: 'S' } },
      { id: 'var_31_m', title: 'M', price: 1199000, available: true, options: { size: 'M' } },
      { id: 'var_31_l', title: 'L', price: 1199000, available: true, options: { size: 'L' } },
    ],
    tags: ['куртки', 'тренч', 'классика'],
    vendor: 'Merfy Classic',
    productType: 'Куртки',
  },
  {
    id: 'prod_32',
    handle: 'corduroy-shirt',
    title: 'Вельветовая рубашка',
    description: 'Рубашка из мягкого вельвета.',
    price: 419000,
    images: [{ url: placeholder(32), alt: 'Вельветовая рубашка' }],
    variants: [
      { id: 'var_32_m', title: 'M', price: 419000, available: true, options: { size: 'M' } },
      { id: 'var_32_l', title: 'L', price: 419000, available: true, options: { size: 'L' } },
    ],
    tags: ['рубашки', 'вельвет', 'осень'],
    vendor: 'Merfy Basics',
    productType: 'Рубашки',
  },
  {
    id: 'prod_33',
    handle: 'pleated-skirt',
    title: 'Плиссированная юбка',
    description: 'Юбка-плиссе длиной миди.',
    price: 439000,
    images: [{ url: placeholder(33), alt: 'Плиссированная юбка' }],
    variants: [
      { id: 'var_33_xs', title: 'XS', price: 439000, available: true, options: { size: 'XS' } },
      { id: 'var_33_s', title: 'S', price: 439000, available: true, options: { size: 'S' } },
      { id: 'var_33_m', title: 'M', price: 439000, available: true, options: { size: 'M' } },
    ],
    tags: ['юбки', 'плиссе', 'миди'],
    vendor: 'Merfy Style',
    productType: 'Юбки',
  },
  {
    id: 'prod_34',
    handle: 'tank-top',
    title: 'Топ на бретелях',
    description: 'Базовый топ из хлопкового трикотажа.',
    price: 149000,
    images: [{ url: placeholder(34), alt: 'Топ на бретелях' }],
    variants: [
      { id: 'var_34_xs', title: 'XS', price: 149000, available: true, options: { size: 'XS' } },
      { id: 'var_34_s', title: 'S', price: 149000, available: true, options: { size: 'S' } },
      { id: 'var_34_m', title: 'M', price: 149000, available: true, options: { size: 'M' } },
      { id: 'var_34_l', title: 'L', price: 149000, available: true, options: { size: 'L' } },
    ],
    tags: ['топы', 'базовый', 'лето'],
    vendor: 'Merfy Basics',
    productType: 'Топы',
  },
  {
    id: 'prod_35',
    handle: 'puffer-vest',
    title: 'Дутый жилет',
    description: 'Легкий дутый жилет с синтепоновым наполнителем.',
    price: 479000,
    images: [{ url: placeholder(35), alt: 'Дутый жилет' }],
    variants: [
      { id: 'var_35_m', title: 'M', price: 479000, available: true, options: { size: 'M' } },
      { id: 'var_35_l', title: 'L', price: 479000, available: true, options: { size: 'L' } },
    ],
    tags: ['жилеты', 'дутый', 'осень'],
    vendor: 'Merfy Outerwear',
    productType: 'Жилеты',
  },
  {
    id: 'prod_36',
    handle: 'watch-classic',
    title: 'Классические часы',
    description: 'Кварцевые часы с кожаным ремешком.',
    price: 999000,
    compareAtPrice: 1299000,
    images: [{ url: placeholder(36), alt: 'Классические часы' }],
    variants: [
      { id: 'var_36_default', title: 'Один размер', price: 999000, available: true },
    ],
    tags: ['аксессуары', 'часы', 'подарок'],
    vendor: 'Merfy Accessories',
    productType: 'Аксессуары',
  },
  {
    id: 'prod_37',
    handle: 'crop-top',
    title: 'Кроп-топ',
    description: 'Укороченный топ спортивного кроя.',
    price: 179000,
    images: [{ url: placeholder(37), alt: 'Кроп-топ' }],
    variants: [
      { id: 'var_37_xs', title: 'XS', price: 179000, available: true, options: { size: 'XS' } },
      { id: 'var_37_s', title: 'S', price: 179000, available: true, options: { size: 'S' } },
      { id: 'var_37_m', title: 'M', price: 179000, available: true, options: { size: 'M' } },
    ],
    tags: ['топы', 'кроп', 'спорт'],
    vendor: 'Merfy Active',
    productType: 'Топы',
  },
  {
    id: 'prod_38',
    handle: 'leather-jacket',
    title: 'Кожаная куртка',
    description: 'Куртка из натуральной кожи в байкерском стиле.',
    price: 1599000,
    images: [{ url: placeholder(38), alt: 'Кожаная куртка' }],
    variants: [
      { id: 'var_38_s', title: 'S', price: 1599000, available: true, options: { size: 'S' } },
      { id: 'var_38_m', title: 'M', price: 1599000, available: true, options: { size: 'M' } },
      { id: 'var_38_l', title: 'L', price: 1599000, available: false, options: { size: 'L' } },
    ],
    tags: ['куртки', 'кожа', 'байкер'],
    vendor: 'Merfy Outerwear',
    productType: 'Куртки',
  },
  {
    id: 'prod_39',
    handle: 'formal-shirt',
    title: 'Рубашка формальная',
    description: 'Белая рубашка из хлопка с манжетами под запонки.',
    price: 349000,
    images: [{ url: placeholder(39), alt: 'Рубашка формальная' }],
    variants: [
      { id: 'var_39_s', title: 'S', price: 349000, available: true, options: { size: 'S' } },
      { id: 'var_39_m', title: 'M', price: 349000, available: true, options: { size: 'M' } },
      { id: 'var_39_l', title: 'L', price: 349000, available: true, options: { size: 'L' } },
    ],
    tags: ['рубашки', 'формальный', 'офис'],
    vendor: 'Merfy Classic',
    productType: 'Рубашки',
  },
  {
    id: 'prod_40',
    handle: 'backpack-urban',
    title: 'Городской рюкзак',
    description: 'Рюкзак из водоотталкивающего нейлона.',
    price: 459000,
    images: [{ url: placeholder(40), alt: 'Городской рюкзак' }],
    variants: [
      { id: 'var_40_default', title: 'Один размер', price: 459000, available: true },
    ],
    tags: ['сумки', 'рюкзак', 'городской'],
    vendor: 'Merfy Accessories',
    productType: 'Сумки',
  },
  {
    id: 'prod_41',
    handle: 'velvet-blazer',
    title: 'Бархатный блейзер',
    description: 'Блейзер из бархата для вечерних выходов.',
    price: 1099000,
    images: [{ url: placeholder(41), alt: 'Бархатный блейзер' }],
    variants: [
      { id: 'var_41_s', title: 'S', price: 1099000, available: true, options: { size: 'S' } },
      { id: 'var_41_m', title: 'M', price: 1099000, available: true, options: { size: 'M' } },
    ],
    tags: ['пиджаки', 'бархат', 'вечер'],
    vendor: 'Merfy Classic',
    productType: 'Пиджаки',
  },
  {
    id: 'prod_42',
    handle: 'thermal-underwear',
    title: 'Термобелье комплект',
    description: 'Комплект термобелья из шерсти мерино.',
    price: 599000,
    images: [{ url: placeholder(42), alt: 'Термобелье комплект' }],
    variants: [
      { id: 'var_42_s', title: 'S', price: 599000, available: true, options: { size: 'S' } },
      { id: 'var_42_m', title: 'M', price: 599000, available: true, options: { size: 'M' } },
      { id: 'var_42_l', title: 'L', price: 599000, available: true, options: { size: 'L' } },
    ],
    tags: ['белье', 'термо', 'зима'],
    vendor: 'Merfy Active',
    productType: 'Белье',
  },
  {
    id: 'prod_43',
    handle: 'flip-flops',
    title: 'Шлепанцы',
    description: 'Легкие шлепанцы для пляжа и бассейна.',
    price: 89000,
    images: [{ url: placeholder(43), alt: 'Шлепанцы' }],
    variants: [
      { id: 'var_43_39', title: '39', price: 89000, available: true, options: { size: '39' } },
      { id: 'var_43_41', title: '41', price: 89000, available: true, options: { size: '41' } },
      { id: 'var_43_43', title: '43', price: 89000, available: true, options: { size: '43' } },
    ],
    tags: ['обувь', 'шлепанцы', 'лето'],
    vendor: 'Merfy Shoes',
    productType: 'Обувь',
  },
  {
    id: 'prod_44',
    handle: 'lace-bralette',
    title: 'Кружевной бралетт',
    description: 'Нежный бралетт из французского кружева.',
    price: 219000,
    images: [{ url: placeholder(44), alt: 'Кружевной бралетт' }],
    variants: [
      { id: 'var_44_xs', title: 'XS', price: 219000, available: true, options: { size: 'XS' } },
      { id: 'var_44_s', title: 'S', price: 219000, available: true, options: { size: 'S' } },
      { id: 'var_44_m', title: 'M', price: 219000, available: true, options: { size: 'M' } },
    ],
    tags: ['белье', 'кружево'],
    vendor: 'Merfy Intimates',
    productType: 'Белье',
  },
  {
    id: 'prod_45',
    handle: 'denim-shorts',
    title: 'Джинсовые шорты',
    description: 'Короткие шорты из светлого денима.',
    price: 299000,
    images: [{ url: placeholder(45), alt: 'Джинсовые шорты' }],
    variants: [
      { id: 'var_45_xs', title: 'XS', price: 299000, available: true, options: { size: 'XS' } },
      { id: 'var_45_s', title: 'S', price: 299000, available: true, options: { size: 'S' } },
      { id: 'var_45_m', title: 'M', price: 299000, available: true, options: { size: 'M' } },
    ],
    tags: ['шорты', 'деним', 'лето'],
    vendor: 'Merfy Denim',
    productType: 'Шорты',
  },
  {
    id: 'prod_46',
    handle: 'wool-coat',
    title: 'Шерстяное пальто',
    description: 'Пальто оверсайз из итальянской шерсти.',
    price: 1899000,
    images: [{ url: placeholder(46), alt: 'Шерстяное пальто' }],
    variants: [
      { id: 'var_46_s', title: 'S', price: 1899000, available: true, options: { size: 'S' } },
      { id: 'var_46_m', title: 'M', price: 1899000, available: true, options: { size: 'M' } },
      { id: 'var_46_l', title: 'L', price: 1899000, available: false, options: { size: 'L' } },
    ],
    tags: ['пальто', 'шерсть', 'зима'],
    vendor: 'Merfy Outerwear',
    productType: 'Пальто',
  },
  {
    id: 'prod_47',
    handle: 'canvas-belt',
    title: 'Тканевый ремень',
    description: 'Ремень из плотного канваса с металлической пряжкой.',
    price: 129000,
    images: [{ url: placeholder(47), alt: 'Тканевый ремень' }],
    variants: [
      { id: 'var_47_default', title: 'Один размер', price: 129000, available: true },
    ],
    tags: ['аксессуары', 'ремни'],
    vendor: 'Merfy Accessories',
    productType: 'Аксессуары',
  },
  {
    id: 'prod_48',
    handle: 'henley-shirt',
    title: 'Рубашка Хенли',
    description: 'Рубашка с воротником-стойкой из тонкого хлопка.',
    price: 299000,
    images: [{ url: placeholder(48), alt: 'Рубашка Хенли' }],
    variants: [
      { id: 'var_48_s', title: 'S', price: 299000, available: true, options: { size: 'S' } },
      { id: 'var_48_m', title: 'M', price: 299000, available: true, options: { size: 'M' } },
      { id: 'var_48_l', title: 'L', price: 299000, available: true, options: { size: 'L' } },
    ],
    tags: ['рубашки', 'хенли', 'базовый'],
    vendor: 'Merfy Basics',
    productType: 'Рубашки',
  },
  {
    id: 'prod_49',
    handle: 'palazzo-pants',
    title: 'Палаццо',
    description: 'Широкие брюки палаццо из струящейся ткани.',
    price: 519000,
    images: [{ url: placeholder(49), alt: 'Палаццо' }],
    variants: [
      { id: 'var_49_s', title: 'S', price: 519000, available: true, options: { size: 'S' } },
      { id: 'var_49_m', title: 'M', price: 519000, available: true, options: { size: 'M' } },
    ],
    tags: ['брюки', 'палаццо', 'лето'],
    vendor: 'Merfy Style',
    productType: 'Брюки',
  },
  {
    id: 'prod_50',
    handle: 'sports-bra',
    title: 'Спортивный топ',
    description: 'Спортивный топ с поддержкой средней интенсивности.',
    price: 249000,
    images: [{ url: placeholder(50), alt: 'Спортивный топ' }],
    variants: [
      { id: 'var_50_xs', title: 'XS', price: 249000, available: true, options: { size: 'XS' } },
      { id: 'var_50_s', title: 'S', price: 249000, available: true, options: { size: 'S' } },
      { id: 'var_50_m', title: 'M', price: 249000, available: true, options: { size: 'M' } },
      { id: 'var_50_l', title: 'L', price: 249000, available: true, options: { size: 'L' } },
    ],
    tags: ['спорт', 'топы', 'фитнес'],
    vendor: 'Merfy Active',
    productType: 'Спорт',
  },
  {
    id: 'prod_51',
    handle: 'winter-boots',
    title: 'Зимние ботинки',
    description: 'Утепленные ботинки на толстой подошве.',
    price: 899000,
    images: [{ url: placeholder(51), alt: 'Зимние ботинки' }],
    variants: [
      { id: 'var_51_38', title: '38', price: 899000, available: true, options: { size: '38' } },
      { id: 'var_51_39', title: '39', price: 899000, available: true, options: { size: '39' } },
      { id: 'var_51_40', title: '40', price: 899000, available: true, options: { size: '40' } },
      { id: 'var_51_41', title: '41', price: 899000, available: false, options: { size: '41' } },
    ],
    tags: ['обувь', 'ботинки', 'зима'],
    vendor: 'Merfy Shoes',
    productType: 'Обувь',
  },
  {
    id: 'prod_52',
    handle: 'satin-pajama',
    title: 'Атласная пижама',
    description: 'Комплект пижамы из атласа: рубашка и брюки.',
    price: 459000,
    images: [{ url: placeholder(52), alt: 'Атласная пижама' }],
    variants: [
      { id: 'var_52_s', title: 'S', price: 459000, available: true, options: { size: 'S' } },
      { id: 'var_52_m', title: 'M', price: 459000, available: true, options: { size: 'M' } },
      { id: 'var_52_l', title: 'L', price: 459000, available: true, options: { size: 'L' } },
    ],
    tags: ['белье', 'пижама', 'атлас'],
    vendor: 'Merfy Intimates',
    productType: 'Белье',
  },
];
