import { Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { promises as fs } from "fs";
import * as path from "path";

/**
 * TraefikRouterService — provisioning сайта БЕЗ создания per-site Coolify-app.
 *
 * Вместо контейнера-на-сайт пишет per-site Traefik dynamic-config роутер
 * (`Host(<slug>.merfy.ru)` → центральный прокси `merfy-sites-shared`), который
 * Traefik подхватывает hot-reload'ом (file-провайдер). Новый домен получает
 * LE-сертификат по HTTP-01 сам (TLS как был, без wildcard/DNS-01).
 *
 * Каталог dynamic-config монтируется в контейнер sites (хост
 * `/data/coolify/proxy/dynamic`). Включается флагом SITES_USE_CENTRAL_PROXY=true.
 *
 * Покрывает только сабдомены `<slug>.merfy.ru` (label == storageSlug == папка
 * MinIO). Кастомные домены — отдельно (per-site app / будущий domain→slug map).
 */
@Injectable()
export class TraefikRouterService {
  private readonly logger = new Logger(TraefikRouterService.name);
  private readonly dir: string;
  private readonly service: string;
  private readonly certResolver: string;

  constructor(private readonly config: ConfigService) {
    this.dir =
      this.config.get<string>("TRAEFIK_DYNAMIC_DIR") ?? "/srv/traefik-dynamic";
    this.service =
      this.config.get<string>("SITES_PROXY_SERVICE") ?? "merfy-sites-shared";
    this.certResolver =
      this.config.get<string>("SITES_CERT_RESOLVER") ?? "letsencrypt";
  }

  /** Включён ли режим центрального прокси (иначе — старый per-site app). */
  get enabled(): boolean {
    return this.config.get<string>("SITES_USE_CENTRAL_PROXY") === "true";
  }

  private fileFor(slug: string): string {
    return path.join(this.dir, `site-${slug}.yml`);
  }

  /**
   * Idempotent — пишет/обновляет роутер сайта. Возвращает публичный URL.
   * Slug идёт в имя файла, имя роутера и Host → допускаем только [a-z0-9-].
   */
  async ensureSiteRouter(slug: string): Promise<string> {
    if (!/^[a-z0-9-]+$/.test(slug)) {
      throw new Error(`ensureSiteRouter: invalid slug '${slug}'`);
    }
    const host = `${slug}.merfy.ru`;
    const yaml = `# auto-generated by sites TraefikRouterService — do not edit by hand
http:
  routers:
    s-${slug}:
      rule: Host(\`${host}\`)
      service: ${this.service}
      entryPoints:
        - https
      priority: 1000
      tls:
        certResolver: ${this.certResolver}
`;
    await fs.mkdir(this.dir, { recursive: true });
    await fs.writeFile(this.fileFor(slug), yaml, "utf8");
    this.logger.log(`Traefik router ensured: ${host} (site-${slug}.yml)`);
    return `https://${host}`;
  }

  /** Удаляет роутер сайта (при удалении сайта). Не бросает если файла нет. */
  async removeSiteRouter(slug: string): Promise<void> {
    try {
      await fs.unlink(this.fileFor(slug));
      this.logger.log(`Traefik router removed: site-${slug}.yml`);
    } catch (e) {
      const err = e as NodeJS.ErrnoException;
      if (err?.code === "ENOENT") return;
      this.logger.warn(
        `removeSiteRouter failed for ${slug}: ${err?.message ?? String(e)}`,
      );
    }
  }
}
