import { Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { promises as fs } from "fs";
import * as path from "path";
import { buildSiteHost } from "../common/site-domain";

/**
 * TraefikRouterService — provisioning сайта БЕЗ создания per-site Coolify-app.
 *
 * Вместо контейнера-на-сайт пишет per-site Traefik dynamic-config роутер
 * (`Host(<slug>.merfy.ru)` → центральный прокси `merfy-sites-shared`), который
 * Traefik подхватывает hot-reload'ом (file-провайдер). Новый домен получает
 * LE-сертификат по HTTP-01 сам (TLS как был, без wildcard/DNS-01).
 *
 * Каталог dynamic-config монтируется в контейнер sites (хост
 * `/data/coolify/proxy/dynamic`). Включается флагом SITES_USE_CENTRAL_PROXY=true.
 *
 * Покрывает только сабдомены `<slug>.merfy.ru` (label == storageSlug == папка
 * MinIO). Кастомные домены — отдельно (per-site app / будущий domain→slug map).
 */
@Injectable()
export class TraefikRouterService {
  private readonly logger = new Logger(TraefikRouterService.name);
  private readonly dir: string;
  private readonly service: string;
  private readonly certResolver: string;
  private readonly filePrefix: string;
  private readonly wildcard: string;

  constructor(private readonly config: ConfigService) {
    this.dir =
      this.config.get<string>("TRAEFIK_DYNAMIC_DIR") ?? "/srv/traefik-dynamic";
    this.service =
      this.config.get<string>("SITES_PROXY_SERVICE") ?? "merfy-sites-shared";
    this.certResolver =
      this.config.get<string>("SITES_CERT_RESOLVER") ?? "letsencrypt";
    // Контур (spec 116). У прода дефолты дают прежние файлы байт в байт. У dev — свой префикс
    // файла и имени роутера (иначе dev перезаписал бы роутер прода того же слага в общем
    // каталоге Traefik) и wildcard-сертификат, чтобы сотни dev-витрин не тратили лимит LE.
    this.filePrefix = this.config.get<string>("SITES_TRAEFIK_FILE_PREFIX") ?? "site-";
    this.wildcard = this.config.get<string>("SITES_CERT_WILDCARD") ?? "";
  }

  /** Включён ли режим центрального прокси (иначе — старый per-site app). */
  get enabled(): boolean {
    return this.config.get<string>("SITES_USE_CENTRAL_PROXY") === "true";
  }

  private fileFor(slug: string): string {
    return path.join(this.dir, `${this.filePrefix}${slug}.yml`);
  }

  /** Имя роутера: прод — `s-<slug>` как раньше, другой контур — `<префикс><slug>`. */
  private routerName(slug: string): string {
    return this.filePrefix === "site-" ? `s-${slug}` : `${this.filePrefix}${slug}`;
  }

  /** Блок tls роутера: с wildcard — один сертификат на все витрины контура. */
  private tlsBlock(): string {
    const resolver = `      tls:\n        certResolver: ${this.certResolver}\n`;
    return this.wildcard ? `${resolver}        domains:\n          - main: "${this.wildcard}"\n` : resolver;
  }

  /**
   * Idempotent — пишет/обновляет роутер сайта. Возвращает публичный URL.
   * Slug идёт в имя файла, имя роутера и Host → допускаем только [a-z0-9-].
   */
  async ensureSiteRouter(slug: string): Promise<string> {
    if (!/^[a-z0-9-]+$/.test(slug)) {
      throw new Error(`ensureSiteRouter: invalid slug '${slug}'`);
    }
    const host = buildSiteHost(slug);
    const yaml = `# auto-generated by sites TraefikRouterService — do not edit by hand
http:
  routers:
    ${this.routerName(slug)}:
      rule: Host(\`${host}\`)
      service: ${this.service}
      entryPoints:
        - https
      priority: 1000
${this.tlsBlock()}`;
    await fs.mkdir(this.dir, { recursive: true });
    await fs.writeFile(this.fileFor(slug), yaml, "utf8");
    this.logger.log(`Traefik router ensured: ${host} (${this.filePrefix}${slug}.yml)`);
    return `https://${host}`;
  }

  /** Удаляет роутер сайта (при удалении сайта). Не бросает если файла нет. */
  async removeSiteRouter(slug: string): Promise<void> {
    try {
      await fs.unlink(this.fileFor(slug));
      this.logger.log(`Traefik router removed: ${this.filePrefix}${slug}.yml`);
    } catch (e) {
      const err = e as NodeJS.ErrnoException;
      if (err?.code === "ENOENT") return;
      this.logger.warn(
        `removeSiteRouter failed for ${slug}: ${err?.message ?? String(e)}`,
      );
    }
  }
}
