import { TOKEN_REGISTRY, type TokenKey } from './registry';
import { BASE_DEFAULTS } from './base-defaults';

export interface ThemeInputForCss {
  id: string;
  defaults: Partial<Record<TokenKey, string>>;
  colorSchemes: Array<{
    id: string;
    name: string;
    tokens: Partial<Record<TokenKey, string>>;
  }>;
  features: Record<string, boolean>;
}

export function generateTokensCssV2(
  theme: ThemeInputForCss,
  merchantOverrides: Partial<Record<TokenKey, string>>,
  _options: Record<string, unknown> = {},
): string {
  // Validate all keys
  validateKeys(theme.defaults, 'theme.defaults');
  validateKeys(merchantOverrides, 'merchantOverrides');
  for (const s of theme.colorSchemes) {
    validateKeys(s.tokens, `colorScheme ${s.id}`);
  }

  const merged: Record<string, string> = { ...BASE_DEFAULTS, ...theme.defaults, ...merchantOverrides };

  const lines: string[] = [];
  lines.push('/* Auto-generated by @merfy/theme-contract. Do not edit. */');
  lines.push(':root {');
  for (const [k, v] of Object.entries(merged)) {
    lines.push(`  ${k}: ${v};`);
  }
  lines.push('}');

  for (let i = 0; i < theme.colorSchemes.length; i++) {
    const s = theme.colorSchemes[i];
    lines.push('');
    lines.push(`.color-scheme-${i + 1} {`);
    for (const [k, v] of Object.entries(s.tokens)) {
      lines.push(`  ${k}: ${v};`);
    }
    lines.push('}');
  }

  lines.push('');
  for (const [feature, enabled] of Object.entries(theme.features)) {
    lines.push(`:root { --feature-${feature}: ${enabled ? 1 : 0}; }`);
  }

  return lines.join('\n');
}

function validateKeys(obj: Partial<Record<TokenKey, string>>, context: string): void {
  for (const key of Object.keys(obj)) {
    if (!(key in TOKEN_REGISTRY)) {
      throw new Error(`Unknown token "${key}" in ${context}. Must be in TOKEN_REGISTRY.`);
    }
  }
}
