/**
 * Tests for tokens-generator.ts
 *
 * Validates:
 * - Hex to RGB triplet conversion
 * - CSS custom property generation
 * - Merchant settings merging with theme defaults
 * - Color scheme class generation
 * - Font family, font size, border radius tokens
 * - Custom CSS appending
 */

import {
  generateTokensCss,
  toRgbTriplet,
  type MerchantSettings,
  type ThemeDefaults,
  type ColorScheme,
} from "../tokens-generator";

// -- toRgbTriplet tests --

describe("toRgbTriplet", () => {
  it("converts 6-digit hex to RGB triplet", () => {
    expect(toRgbTriplet("#ff5733")).toBe("255 87 51");
  });

  it("converts 3-digit hex shorthand", () => {
    expect(toRgbTriplet("#fff")).toBe("255 255 255");
  });

  it("converts 8-digit hex (with alpha) taking only RGB", () => {
    expect(toRgbTriplet("#ff573380")).toBe("255 87 51");
  });

  it("passes through already-formatted RGB triplets", () => {
    expect(toRgbTriplet("255 87 51")).toBe("255 87 51");
  });

  it("converts rgb() function notation", () => {
    expect(toRgbTriplet("rgb(255, 87, 51)")).toBe("255 87 51");
  });

  it("converts rgba() function notation", () => {
    expect(toRgbTriplet("rgba(255, 87, 51, 0.5)")).toBe("255 87 51");
  });

  it("returns original string for unparseable values", () => {
    expect(toRgbTriplet("transparent")).toBe("transparent");
  });

  it("trims whitespace", () => {
    expect(toRgbTriplet("  #000  ")).toBe("0 0 0");
  });

  it("converts black hex", () => {
    expect(toRgbTriplet("#000000")).toBe("0 0 0");
  });
});

// -- generateTokensCss tests --

describe("generateTokensCss", () => {
  it("includes auto-generated comment header", () => {
    const css = generateTokensCss({});
    expect(css).toContain("Auto-generated by Merfy");
  });

  it("generates :root block with token properties", () => {
    const settings: MerchantSettings = {
      tokens: {
        "primary-color": "#ff5733",
        spacing: "16px",
      },
    };

    const css = generateTokensCss(settings);

    expect(css).toContain(":root {");
    expect(css).toContain("--primary-color:");
    expect(css).toContain("--spacing: 16px;");
  });

  it("converts color tokens to RGB triplets", () => {
    const settings: MerchantSettings = {
      tokens: {
        "primary-color": "#ff5733",
      },
    };

    const css = generateTokensCss(settings);

    // Color-like key name should trigger RGB conversion
    expect(css).toContain("255 87 51");
  });

  it("does not convert non-color tokens to RGB", () => {
    const settings: MerchantSettings = {
      tokens: {
        "max-width": "1200px",
      },
    };

    const css = generateTokensCss(settings);

    expect(css).toContain("--max-width: 1200px;");
  });

  it("generates font-family custom property", () => {
    const settings: MerchantSettings = {
      fontFamily: "'Inter', sans-serif",
    };

    const css = generateTokensCss(settings);

    expect(css).toContain("--font-family: 'Inter', sans-serif;");
  });

  it("generates font-size-base custom property", () => {
    const settings: MerchantSettings = {
      fontSizeBase: 16,
    };

    const css = generateTokensCss(settings);

    expect(css).toContain("--font-size-base: 16px;");
  });

  it("generates border-radius custom property", () => {
    const settings: MerchantSettings = {
      borderRadius: 8,
    };

    const css = generateTokensCss(settings);

    expect(css).toContain("--border-radius: 8px;");
  });

  it("generates .color-scheme-N classes", () => {
    const settings: MerchantSettings = {
      colorSchemes: [
        {
          id: 1,
          label: "Light",
          colors: {
            background: "#ffffff",
            text: "#333333",
          },
        },
        {
          id: 2,
          label: "Dark",
          colors: {
            background: "#1a1a1a",
            text: "#ffffff",
          },
        },
      ],
    };

    const css = generateTokensCss(settings);

    expect(css).toContain(".color-scheme-1");
    expect(css).toContain(".color-scheme-2");
    expect(css).toContain("/* Light */");
    expect(css).toContain("/* Dark */");
  });

  it("converts color scheme colors to RGB triplets", () => {
    const settings: MerchantSettings = {
      colorSchemes: [
        {
          id: 1,
          colors: { background: "#ffffff" },
        },
      ],
    };

    const css = generateTokensCss(settings);

    expect(css).toContain("255 255 255");
  });

  it("merges merchant settings with theme defaults", () => {
    const merchant: MerchantSettings = {
      tokens: { "primary-color": "#ff0000" },
    };
    const defaults: ThemeDefaults = {
      tokens: { "primary-color": "#0000ff", "secondary-color": "#00ff00" },
      fontFamily: "Arial",
    };

    const css = generateTokensCss(merchant, defaults);

    // Merchant primary-color overrides default
    expect(css).toContain("255 0 0"); // #ff0000
    expect(css).not.toContain("0 0 255"); // #0000ff overridden
    // Default secondary-color preserved
    expect(css).toContain("0 255 0"); // #00ff00
    // Default fontFamily preserved
    expect(css).toContain("--font-family: Arial;");
  });

  it("appends custom CSS at the end", () => {
    const settings: MerchantSettings = {
      customCss: ".custom { color: red; }",
    };

    const css = generateTokensCss(settings);

    expect(css).toContain("/* Custom CSS */");
    expect(css).toContain(".custom { color: red; }");
  });

  it("concatenates default + merchant custom CSS", () => {
    const merchant: MerchantSettings = {
      customCss: ".merchant { display: block; }",
    };
    const defaults: ThemeDefaults = {
      customCss: ".default { display: flex; }",
    };

    const css = generateTokensCss(merchant, defaults);

    expect(css).toContain(".default { display: flex; }");
    expect(css).toContain(".merchant { display: block; }");
  });

  it("handles empty settings gracefully", () => {
    const css = generateTokensCss({});

    expect(css).toContain("Auto-generated by Merfy");
    // Should not throw
    expect(typeof css).toBe("string");
  });

  it("handles border radius of 0", () => {
    const settings: MerchantSettings = {
      borderRadius: 0,
    };

    const css = generateTokensCss(settings);

    expect(css).toContain("--border-radius: 0px;");
  });
});
