import { promises as fs } from "fs";
import * as os from "os";
import * as path from "path";
import { ConfigService } from "@nestjs/config";
import { TraefikRouterService } from "../traefik-router.service";

function make(env: Record<string, string>) {
  const cfg = { get: (k: string) => env[k] } as unknown as ConfigService;
  return new TraefikRouterService(cfg);
}

describe("TraefikRouterService: контур из env", () => {
  let dir: string;
  beforeEach(async () => {
    dir = await fs.mkdtemp(path.join(os.tmpdir(), "traefik-"));
  });

  it("по умолчанию пишет прод-роутер байт в байт как раньше", async () => {
    const svc = make({ SITES_USE_CENTRAL_PROXY: "true", TRAEFIK_DYNAMIC_DIR: dir });
    await expect(svc.ensureSiteRouter("abc123")).resolves.toBe("https://abc123.merfy.ru");
    const yaml = await fs.readFile(path.join(dir, "site-abc123.yml"), "utf8");
    expect(yaml).toBe(
      "# auto-generated by sites TraefikRouterService — do not edit by hand\n" +
        "http:\n  routers:\n    s-abc123:\n      rule: Host(`abc123.merfy.ru`)\n      service: merfy-sites-shared\n" +
        "      entryPoints:\n        - https\n      priority: 1000\n      tls:\n        certResolver: letsencrypt\n",
    );
  });

  it("в dev: свой домен, префикс файла и роутера, резолвер с wildcard", async () => {
    // домен витрин читает src/common/site-domain.ts из process.env на каждый вызов
    process.env.SITES_WILDCARD_DOMAIN = "dev.merfy.ru";
    const svc = make({
      SITES_USE_CENTRAL_PROXY: "true",
      TRAEFIK_DYNAMIC_DIR: dir,
      SITES_TRAEFIK_FILE_PREFIX: "dev-site-",
      SITES_PROXY_SERVICE: "merfy-sites-shared-dev",
      SITES_CERT_RESOLVER: "ledns",
      SITES_CERT_WILDCARD: "*.dev.merfy.ru",
    });
    await expect(svc.ensureSiteRouter("abc123")).resolves.toBe("https://abc123.dev.merfy.ru");
    const yaml = await fs.readFile(path.join(dir, "dev-site-abc123.yml"), "utf8");
    expect(yaml).toContain("    dev-site-abc123:\n      rule: Host(`abc123.dev.merfy.ru`)\n      service: merfy-sites-shared-dev\n");
    expect(yaml).toContain('certResolver: ledns\n        domains:\n          - main: "*.dev.merfy.ru"\n');
    await svc.removeSiteRouter("abc123");
    await expect(fs.access(path.join(dir, "dev-site-abc123.yml"))).rejects.toBeTruthy();
    delete process.env.SITES_WILDCARD_DOMAIN;
  });
});
