export const CheckoutDeliveryMethodTokens = [
  '--color-input-bg',
  '--color-input-border',
  '--color-accent',
  '--color-heading',
  '--color-text',
  '--color-muted',
  '--font-heading',
  '--font-body',
  '--size-h3',
  '--size-body',
  '--size-small',
  '--size-tiny',
  '--radius-input',
  '--color-bg',
  '--color-error',
] as const satisfies readonly `--${string}`[];
