export const CheckoutOrderSummaryTokens = [
  '--color-input-border',
  '--color-input-bg',
  '--color-accent',
  '--color-accent-fg',
  '--color-heading',
  '--color-text',
  '--color-muted',
  '--color-error',
  '--color-button-bg',
  '--color-button-text',
  '--font-heading',
  '--font-body',
  '--size-h3',
  '--size-body',
  '--size-small',
  '--radius-input',
  '--radius-button',
] as const satisfies readonly `--${string}`[];
