import { describe, expect, it } from 'vitest';
import * as api from '../src/index';

describe('API пакета (design.md, раздел 9)', () => {
  it('отдаёт ровно эти имена', () => {
    expect(Object.keys(api).sort()).toEqual([
      'TokenError',
      'checkEdits',
      'choiceAttributes',
      'classesOf',
      'compactEdits',
      'contrastIssues',
      'createTokensTool',
      'dependentsOf',
      'dictionaryJsonSchema',
      'emitCss',
      'extendDictionary',
      'fieldVisible',
      'groupsOf',
      'isSettingField',
      'isTokenField',
      'limitsOf',
      'mergeEdits',
      'panelFields',
      'panelForTheme',
      'panelJsonSchema',
      'parseDictionary',
      'parsePanel',
      'parseSettingsEdits',
      'parseTheme',
      'parseTokenEdits',
      'platformDictionary',
      'readSettingsEdits',
      'readTokenEdits',
      'resolveSettings',
      'resolveTokens',
      'runTokensTool',
      'searchCatalog',
      'searchTokens',
      'settingFields',
      'sourceOf',
      'tailwindCss',
      'themeTokensJsonSchema',
      'tokenFields',
      'tokensCss',
      'tokensMarkdown',
      'tokensTool',
    ]);
  });
});
