export const OrderConfirmationTokens = [
  '--color-bg',
  '--color-text',
  '--color-heading',
  '--color-muted',
  '--color-border',
  '--color-input-bg',
  '--color-button-bg',
  '--color-button-text',
  '--color-accent',
  '--color-error',
  '--font-heading',
  '--font-body',
  '--weight-heading',
  '--weight-body',
  '--size-h2',
  '--size-h3',
  '--size-body',
  '--size-small',
  '--size-tiny',
  '--radius-button',
  '--radius-card',
  '--radius-media',
  // Block-scoped per-section overrides (см. OrderConfirmation.astro — на корне
  // эмитятся с вшитым fallback var(--color-*), поэтому всегда определены).
  '--oc-order-bg',
  '--oc-order-alpha',
  '--oc-summary-bg',
  '--oc-summary-alpha',
  '--oc-accent',
  '--oc-accent-text',
  '--oc-button-bg',
  '--oc-button-text',
  '--oc-error',
] as const satisfies readonly `--${string}`[];
